version: '3.8'

networks:
  board-api-net:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    restart: 'always'
    ports:
      - "3309:3306"
    container_name: board-api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: skyup # root 계정 비밀번호
      MYSQL_DATABASE: board_api_innopam # 초기 생성 데이터베이스
      MYSQL_USER: user # 생성할 사용자 이름
      MYSQL_PASSWORD: skyup # 생성할 사용자 비밀번호
    networks:
      - board-api-net

  server:
    networks:
      - board-api-net
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    ports:
      - "4000:4000"
    container_name: nestjs-bulletin-board-api
    depends_on:
      - mysql